config/routes.rb
Rails.application.routes.draw do
  
    root :to => "home#show"
    
    get '/auth/:provider/callback' => 'login#callback'
    
    resources :notes
    
    resources :payees do
      resources :accounts
    end
    
    
    resources :payments do
      collection do
        get 'filter_list'
        post 'filter_search'
      end
      member do
        put 'paid'
      end
    end
    
    
end

app/models/payment.rb
class Payment

  include Wisper::Publisher

  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :account

  field :amt_cents, type: Integer
  field :due_date, type: Date
  field :reminder, type: Date
  field :payment_paid, type: Boolean
  field :payment_time, type: Time
  field :reminder_status, type: Boolean
  field :reminder_id, type: String

  scope :all_unpaid, -> {where(payment_paid: nil).asc(:due_date)}
  scope :all_paid, -> {ne(payment_paid: nil).asc(:due_date)}

  def self.for_account(acct)
    a = Account.find(acct)
    a.payments
  end

  def create_me(pay: nil, user: nil)
    update_attrs(pay: pay, user: user)
    self.save
    publish(:successful_payment_save_event, self)
  end

  def update_me(pay: nil, user: nil)
    update_attrs(pay: pay, user: user)
    self.save
    publish(:successful_payment_save_event, self)
  end

  def delete_me
    self.destroy
    publish(:successful_payment_delete_event, self)
  end


  def update_attrs(pay: nil, user: nil)
    self.amt = pay[:amt]
    self.due_date = pay[:due_date]
    self.account = Account.find(pay[:account])
    if pay[:reminder].present? && Date.parse(pay[:reminder]) != self.reminder
      reminder = Reminder.new(date: pay[:reminder], payment: self).()
      self.reminder_status = reminder.api_status
      self.reminder_id = reminder.id
      self.reminder = pay[:reminder]
    end
  end

  def paid
    self.payment_paid = true
    self.payment_time = Time.now
    self.save
    publish(:successful_payment_paid_event, self)
  end

  def title
    "Payment: " + "#{self.account.payee.name}"
  end

  def note
    "#{self.amt}"
  end

  def amt=(amt)
    if /^[\d]+(\.[\d]+){0,1}$/ === amt.gsub(/\$/, "")
      money_amt = Monetize.parse(amt, "NZD")
      if [Fixnum, Money].include? money_amt.class
        self.amt_cents = money_amt.cents if money_amt.is_a? Money
      else
        errors.add(:amt, "Amount is not a Money value")
      end
    else
      errors.add(:amt, "Amount does not appear to be a number") unless /^[\d]+(\.[\d]+){0,1}$/ === amt.gsub(/\$/, "")
    end
  end

  def amt(options = {})
    raise ArgumentError, 'The "options" arg must be a Hash' unless options.is_a? Hash
    options[:in] ||= 'NZD'
    self.amt_cents.nil? ? cents = 0 : cents = self.amt_cents
    f = Money.new(cents, options[:in])
  end

  def amount_to_s
    "#{self.amt.currency.symbol}#{self.amt.amount.to_s}"
  end


end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  
  def index
    if params[:filter].present?
      @payments = Payment.all_paid
    else
      @payments = Payment.all_unpaid
    end
  end
  
  def new
    @payment = Payment.new
  end
  
  def create
    @payment = Payment.new
    @payment.subscribe self
    @payment.create_me(pay: params[:payment], user: @current_user_proxy)
  end
  
  def edit
    @payment = Payment.find(params[:id])
  end

  def update
    @payment = Payment.find(params[:id])
    @payment.subscribe self
    @payment.update_me(pay: params[:payment], user: @current_user_proxy)
  end
  
  def destroy
    @payment = Payment.find(params[:id])
    @payment.subscribe self
    @payment.delete_me    
  end
  
  
  def filter_list
  end
  
  def filter_search
    @payments = Payment.for_account(params[:acct_filter])
  end
  
  def paid
    @payment = Payment.find(params[:id])
    @payment.subscribe self
    @payment.paid
  end
  
  
  # Events
  
  def successful_payment_save_event(pay)
    redirect_to payments_path
  end

  def successful_payment_paid_event(pay)
    redirect_to payments_path
  end

  def successful_payment_delete_event(pay)
    redirect_to payments_path
  end
  
  
end

app/views/payments/_filter_form.html.erb
<%= form_tag(filter_search_payments_path, html: { class: "custom"}) do %>
   <div class="row">
     <div class="small-3 columns">
       <%= label_tag :account_filter, nil, class: "right inline"%>
     </div>
     <div class="small-4 columns end">
         <%= select_tag(:acct_filter, options_for_select(account_selector), :include_blank => true, :prompt => "Select an account", id: "filter-select") %>
     </div> 
   </div>
<% end %>

app/views/payments/_form.html.erb
<%= form_for(@payment, html: { class: "custom"}) do |f| %>
   <div class="row">
     <div class="small-3 columns">
       <%= f.label :amount, class: "right inline"%>
     </div>
     <div class="small-5 columns end">
       <%= f.number_field(:amt, min: 0.10, step: 0.01) %>
     </div> 
   </div>
   <div class="row">   
     <div class="small-3 columns">
        <%= f.label :account, class: "right inline"%>
     </div>
     <div class="small-5 columns end">
        <%= select(:payment, :account, options_for_select(account_selector, @payment.account.try(:id)), {include_blank: 'None'}) %>
     </div> 
   </div>
   <div class="row">   
     <div class="small-3 columns">
        <%= f.label :due_date, class: "right inline"%>
     </div>
     <div class="small-5 columns end">
        <%= f.text_field :due_date, :class => "date-picker", :placeholder => "New Date" %>
     </div> 
   </div>
   <div class="row">   
     <div class="small-3 columns">
        <%= f.label :reminder, class: "right inline"%>
     </div>
     <div class="small-5 columns end">
        <%= f.text_field :reminder, :class => "date-picker", :placeholder => "Set Reminder" %>
     </div> 
   </div>
   <div class="row">
     <div class="small-5 small-offset-3 columns">
       <%= f.submit 'Submit', :class => 'button small' %>
     </div>
   </div>
<% end %>

app/views/payments/_icon_bar.html.erb
<div class="icon-bar large-vertical four-up">
   <%= link_to(new_payment_path, class: "item") do %>
      <i class="fi-dollar"></i>
      <label>New Payment</label>
   <% end %>
   <%= link_to(payments_path, class: "item") do %>
      <i class="fi-dollar-bill"></i>
      <label>Payments</label>
   <% end %>
   <%= link_to(filter_list_payments_path, class: "item", remote: true) do %>
      <i class="fi-zoom-out"></i>
      <label>filter</label>
   <% end %>
   <%= link_to(payments_path(filter: :paid), class: "item") do %>
      <i class="fi-zoom-out"></i>
      <label>Payments Paid</label>
   <% end %>
   
</div>

app/views/payments/_payment_panel.html.erb
<div class="row">
   <% if pay.payment_paid %>
      <p class="text-center"><i class="fi-check size-36"></i> Paid</p>
   <% else %>
      <div class="large-4 columns">
         <%= link_to edit_payment_path(pay) do %>
            <i class="fi-page-edit size-36"></i>
         <% end %>
      </div>
      <div class="large-3 columns">
         <%= link_to paid_payment_path(pay), method: :put do %>
            <i class="fi-dollar-bill size-36"></i>
         <% end %>
      </div>
      <div class="large-4 columns">
         <%= link_to payment_path(pay), method: :delete do %>
            <i class="fi-x size-36"></i>
         <% end %>
      </div>
   <% end %>
</div>
<h5 class="text-center"><i class="fi-calendar size-24"></i> <%= pay.due_date%></h5>
<h5 class="subheader text-center"><%= pay.account.payee.name%></h5>
<h6 class="text-center"><%= pay.account.name%></h6>
<h6 class="text-center"><%= number_to_currency(pay.amt)%></h6>
<% if pay.reminder %>
   <p class="text-center">
     <i class="fi-flag"></i>
     <%= pay.reminder%>
     <% if pay.reminder_status %>
      <i class="fi-check"></i>
     <% end %>
   </p>
<% end %>

app/views/payments/_payments.html.erb
<% rows = (@payments.count / 5) + 1 %>
<% (1..rows).each do |row|  %>
   <div class="row">
      <div class="small-11 columns end">
         <ul class="large-block-grid-5">
            <% (0..4).each do |item| %>
               <% indx = ((row - 1) * 5) + item %>
              <li>
                 <% if @payments[indx] %>
                    <div class="panel">
                       <%= render partial: "payment_panel", locals: {pay: @payments[indx]}%>
                    </div>
                  <% end%>
              </li>
            <% end %>
         </ul>
      </div>
   </div>
<% end %>

app/views/payments/edit.html.erb
<div class="row">
   <div class="small-3 columns">
      <%= render "icon_bar"%>
   </div>
   <div class="small-9 columns">
      <div class="row">
         <div id="filter"></div>
      </div>
      <div class="row">
         <%=render partial: "form" %>
      </div>
   </div>
</div>

app/views/payments/index.html.erb
<div class="row">
   <div class="large-3 small-3 columns">
      <%= render "icon_bar"%>
   </div>
   <div class="large-9 small-9 columns">
      <div class="row">
         <div id="filter"></div>
      </div>
      <div class="row">
         <div id="payments">
            <%= render "payments"%> 
         </div>
      </div>
   </div>
</div>

app/views/payments/new.html.erb
<div class="row">
   <div class="small-3 columns">
      <%= render "icon_bar"%>
   </div>
   <div class="small-9 columns">
      <div class="row">
         <div id="filter"></div>
      </div>
      <div class="row">
         <%=render partial: "form" %>
      </div>
   </div>
</div>