config/routes.rb
Rails.application.routes.draw do
  
    root :to => "home#show"
    
    get '/auth/:provider/callback' => 'login#callback'
    
    resources :notes
    
    resources :payees do
      resources :accounts
    end
    
    
    resources :payments do
      collection do
        get 'filter_list'
        post 'filter_search'
      end
      member do
        put 'paid'
      end
    end
    
    
end

app/models/payee.rb
class Payee
  
  include Wisper::Publisher
  
  include Mongoid::Document
  include Mongoid::Timestamps  
  
  has_many :accounts
  
  field :name, type: String

  def create_me(payee: nil)
    update_attrs(payee: payee)
    self.save
    publish(:successful_payee_save_event, self)
  end
  
  def update_me(payee: nil)
    update_attrs(payee: payee)
    self.save
    publish(:successful_payee_save_event, self)
  end
  
  
  def update_attrs(payee: nil)
    self.name = payee[:name]
  end  
  
  def create_acct(acct: nil)
    acct = Account.new.create_me(acct: acct)
    self.accounts << acct
    self.save
    publish(:successful_account_save_event, self)
  end

  def update_acct(id: nil, acct: nil)
    raise if !id
    acct = self.accounts.find(id).update_me(acct: acct)
    self.save
    publish(:successful_account_save_event, self)
  end

  
end

app/controllers/payees_controller.rb
class PayeesController < ApplicationController
  
  def index
    @payees = Payee.all
  end
  
  def new
    @payee = Payee.new
  end
  
  def edit
    @payee = Payee.find(params[:id])
  end
  
  def create
    @payee = Payee.new
    @payee.subscribe self
    @payee.create_me(payee: params[:payee])
  end
  
  def update
    @payee = Payee.find(params[:id])
    @payee.subscribe self
    @payee.update_me(payee: params[:payee])
  end
  
  
  # Events
  
  def successful_payee_save_event(payee)
    redirect_to payees_path
  end
  
  
end

app/views/payees/_form.html.erb
<%= form_for(@payee, html: { class: "custom"}) do |f| %>
   <div class="row">
     <div class="small-2 columns">
       <%= f.label :name, class: "right inline", title: "Whats ya handle", data: {tooltip: true } %>
     </div>
     <div class="small-10 columns">
       <%= f.text_field :name, placeholder: "whats ya handle" %>
     </div> 
   </div>
   <div class="row">
     <div class="small-10 small-offset-2 columns">
       <%= f.submit 'Submit', :class => 'button small' %>
     </div>
   </div>
<% end %>

app/views/payees/_icon_bar.html.erb
<div class="icon-bar large-vertical four-up">
   <%= link_to(new_payee_path, class: "item") do %>
      <i class="fi-widget"></i>
      <label>New Payee</label>
   <% end %>
   <%= link_to(payees_path, class: "item") do %>
      <i class="fi-torso"></i>
      <label>Payees</label>
   <% end %>
</div>

app/views/payees/_payees.html.erb
<table>
  <thead>
    <tr>
      <th>Payee</th>
      <th>Action</th>
    </tr>
  </thead>
   <tbody>
      <% @payees.each do |payee| %>
         <tr>
            <td><%= payee.name%>
               <dl class="sub-nav">   
                  <dt>Accounts</dt>
                  <% payee.accounts.each do |acct|%>
                     <dd class="active"><%= link_to acct.name, edit_payee_account_path(payee, acct) %></a></h4>
                  <% end %>
               </dl>      
            </td>
            
            <td>
               <%= link_to "edit", edit_payee_path(payee), class: "button small"%>
               <%= link_to "New Account", new_payee_account_path(payee), class: "button small"%>               
            </td>            
         </tr>
      <% end %>     
   </tbody>
</table>

app/views/payees/edit.html.erb
<div class="row">
   <div class="small-3 columns">
      <%= render "icon_bar"%>
   </div>
   <div class="small-9 columns">
      <%=render partial: "form" %>
   </div>
</div>

app/views/payees/index.html.erb
<div class="row">
   <div class="small-3 columns">
      <%= render "icon_bar"%>
   </div>
   <div class="small-9 columns">
      <%= render "payees"%>
   </div>
</div>

app/views/payees/new.html.erb
<div class="row">
   <div class="small-3 columns">
      <%= render "icon_bar"%>
   </div>
   <div class="small-9 columns">
      <%=render partial: "form" %>
   </div>
</div>